### ISSUE TITLE
[document] feature 등록 단위에 대한 논의

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/deal-15#1]
issue로 등록되야 하는 feature의 단위는 명확하게 하나의 목적을 가지고 있어야 한다고 생각합니다.

예를 들어서 'ㅇㅇ페이지 만들기 라면
- html 구성하기
- css 구성하기
- javascript 구성하기

와 같이 포괄적인 기능을 나열하는 것이 아닌 구체적으로 작성하는 것을 말합니다.
물론 위 항목에서 더 구체적으로 나열을 하기는 하겠지만 일단은 위와 같이 표현합니다.

구체적으로 'ㅇㅇ페이지 기본 html, css 골격잡기'와 같이 feature를 나누어서 작성했으면 좋겠습니다.

**Comment by TsooranKim** [comment]
예시로

## html 코드 작성
- [ ] header 작성
- [ ] footer 작성
- [ ] 로그인 form 구성

등과 같이 작은 단위에서 하나의 목적에 만 맞게 작성하면 좋겠습니다.

**Comment by momongss** [comment]
동의합니다
