### ISSUE TITLE
[feature] 백엔드 베이스 코드 작성

### ISSUE THREAD

**Issue by momongss** [woowa-techcamp-2021/deal-15#14]
### 기능
- [ ] 폴더 구조 결정
- [ ] .env 로 환경변수 설정 (dotenv 사용)
- [ ] mysql2 연결

**Comment by TsooranKim** [comment]
우선 db는 결정된 사항이 없기 대문에 mysql 연결은 나중에 진행해 주시면 좋겠습니다.

**Comment by momongss** [comment]
> 우선 db는 결정된 사항이 없기 대문에 mysql 연결은 나중에 진행해 주시면 좋겠습니다.

네 알겠습니다!
