### ISSUE TITLE
[document] 기반코드 작성하기

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/deal-15#3]
## 협의되야 하는 항목들
 - [x] 프로젝트에 필요한 package 목록
 - [x] server 기반 구조
 - [x] client 코드를 위한 webpack 기반
 - [x] lint와 formatter 구조 잡기
 - [x] .gitignore 잡기
 - [x] 개발환경 잡고, 필요한 익스텐션들 잡기
 - [x] directory structure 잡기

**Comment by TsooranKim** [comment]
저는 개발환경을 docker로 가상화해서 사용하는데 node버전을 현재 LTS버전인 14버전으로 했으면 합니다.

**Comment by momongss** [comment]
좋습니당

**Comment by TsooranKim** [comment]
eslint와 prettier를 사용하면 좋겠습니다.

**Comment by momongss** [comment]
제가 사용하는 prettier 설정입니다.

.prettierrc
```
{
  "singleQuote": true,
  "semi": true,
  "useTabs": false,
  "tabWidth": 2,
  "trailingComma": "all",
  "printWidth": 100
}
```

**Comment by TsooranKim** [comment]
.editorconfig을 설정하면 좋겠습니다.
vscode에서 [익스텐션](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)을 설치해야 동작합니다.

```
root = true

[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
```

**Comment by TsooranKim** [comment]
베이스 코드의 요구사항
- epxress.js로 서버 기본 코드 작성
- client 코드는 webpack, babel로 분리

**Comment by TsooranKim** [comment]
프로젝트 전체에서 사용할 node 패키지 리스트를 일단 생각해 봤습니다.

### 서버관련
- express.js
- bcrypt
- express-session
- morgan
- debug
- mysql2

### 클라이언트 관련
- webpakc
- babel
- core-js
- sass

### 프로젝트 관련
- eslint
- prettier

**Comment by momongss** [comment]
.gitigore 는 nodejs 에서 자주 사용하는 설정으로 하면 될 것 같습니다.

**Comment by momongss** [comment]
> .editorconfig을 설정하면 좋겠습니다.
> vscode에서 [익스텐션](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)을 설치해야 동작합니다.
> 
> ```
> root = true
> 
> [*]
> end_of_line = lf
> insert_final_newline = true
> indent_style = space
> indent_size = 2
> ```

네. 위 코드는 .editorconfig 파일인 거죠?

**Comment by momongss** [comment]
> 프로젝트 전체에서 사용할 node 패키지 리스트를 일단 생각해 봤습니다.
> 
> ### 서버관련
> * express.js
> * bcrypt
> * express-session
> * morgan
> * debug
> * mysql2
> 
> ### 클라이언트 관련
> * webpakc
> * babel
> * core-js
> * sass
> 
> ### 프로젝트 관련
> * eslint
> * prettier

잘 정리해주셔서 감사합니다.

**Comment by TsooranKim** [comment]
> > .editorconfig을 설정하면 좋겠습니다.
> > vscode에서 [익스텐션](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)을 설치해야 동작합니다.
> > ```
> > root = true
> > 
> > [*]
> > end_of_line = lf
> > insert_final_newline = true
> > indent_style = space
> > indent_size = 2
> > ```
> 
> 네. 위 코드는 .editorconfig 파일인 거죠?

네 맞습니다.

**Comment by momongss** [comment]
eslint 설정 방법입니다.

1. vscode eslint extension [설치](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
2. 터미널에 eslint --init 명령어 입력.
   
![image](https://user-images.githubusercontent.com/37568161/125275340-dc1df280-e349-11eb-97ee-ddc6542f5560.png)

명령어를 입력하면 질문이 나오는데 제가 한 설정(위 사진 참고)과 같이 해주면 되겠습니다.

설정을 마치고 나면 .eslintrc.json 파일이 생성되고
자바스크립트 코드를 확인해보면 eslint 가 오류를 알려주는 걸 확인할 수 있습니다.
아래는 예시 코드입니다. single_q에 빨간 밑줄이 나오면 됩니다.

```
function init() {
  const single_q = "hello world";
  const double_q = "hello world";
  const no_semi = 500;
  console.log("hello world!");
}
init();
```

**Comment by TsooranKim** [comment]
코드를 맨처음에서 express 서버에서 api server와 static file server 역할을 둘다 하게 만들 생각이였으나 레포지토리 내에 client, server 디렉터리를 각각 만들어서 두개의 프로젝트를 만드는 것이 좋겠습니다.

**Comment by TsooranKim** [comment]
#8 eslint, prettier, editorconfig 에 대해서 별도 기록하였습니다.
