### ISSUE TITLE
[document] branch 네이밍, commit 작성 방법

### ISSUE THREAD

**Issue by momongss** [woowa-techcamp-2021/deal-15#4]
## branch 네이밍
- {issue type}/#{issue id}
- bug의 경우, issue : bug / branch : bugfix 로 한다.
- (옵션) - 키워드, 간단한 설명

## commit
- 커밋 단위는 의미있는 단위.
- --amend : 오타 수정 등 간단한 것들은 amend 로 합치기.
- 커밋 메시지는 한글로 적고, 최대한 의미있게.

**Comment by TsooranKim** [comment]
- [commit 작성 요령](https://github.com/woowa-techcamp-2021/deal-15/wiki/commit-%EC%9E%91%EC%84%B1-%EC%9A%94%EB%A0%B9)
- [branch 생성 요령](https://github.com/woowa-techcamp-2021/deal-15/wiki/branch-%EC%83%9D%EC%84%B1-%EC%9A%94%EB%A0%B9)

위키 작성했습니다.
