### ISSUE TITLE
[document] 코어 타임 등 시간 규칙

### ISSUE THREAD

**Issue by momongss** [woowa-techcamp-2021/deal-15#5]
- 몰입 시간 ( 특별한 협업 일정이 없다면 개인 작업에 몰입하는 시간 ) 
  - 14시 ~ 17시
- 서로 안미안해하기 시간
  - 점심시간, 저녁시간
  - 오후 8시 이후

**Comment by TsooranKim** [comment]
네 동의합니다. 위키 [협업하기](https://github.com/woowa-techcamp-2021/deal-15/wiki/%ED%98%91%EC%97%85%ED%95%98%EA%B8%B0)에 정리해 놓도록 하겠습니다.

**Comment by TsooranKim** [comment]
음... 몰입시간 5 ~ 6시까지는 저녁시간이랑 겹쳐서 차라리 14 ~ 17시로 조정하는 것이 좋지 않을까 싶습니다.
또한 "특별한 협업 일정이 없다면"이라는 가정이 있으면 좋겠습니다.

**Comment by momongss** [comment]
> 음... 몰입시간 5 ~ 6시까지는 저녁시간이랑 겹쳐서 차라리 14 ~ 17시로 조정하는 것이 좋지 않을까 싶습니다.
> 또한 "특별한 협업 일정이 없다면"이라는 가정이 있으면 좋겠습니다.

네. 저도 동의합니다. 반영하여 수정했습니다.

**Comment by TsooranKim** [comment]
앗.. 수정은 안해주셔도 됩니다.

**Comment by TsooranKim** [comment]
> 네. 저도 동의합니다. 반영하여 수정했습니다.

앗.. 수정은 안해주셔도 됩니다.
