### ISSUE TITLE
[document] 프로젝트 내에서 directory와 file 이름 규칙에 대한 제안

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/deal-15#50]
directory명과 file 이름은 소문자, 숫자, -를 사용해서 나타내도록 하면 좋겠습니다.

**Comment by momongss** [comment]
동의합니다.!

**Comment by TsooranKim** [comment]
네 [위키](https://github.com/woowa-techcamp-2021/deal-15/wiki/%EB%94%94%EB%A0%89%ED%84%B0%EB%A6%AC%EB%AA%85%EA%B3%BC-%ED%8C%8C%EC%9D%BC-%EC%9D%B4%EB%A6%84-%EA%B7%9C%EC%B9%99)에 등록했습니다.
