### ISSUE TITLE
[feature] 컴포넌트 베이스 코드 변경

### ISSUE THREAD

**Issue by momongss** [woowa-techcamp-2021/deal-15#51]
- 컴포넌트 베이스 코드에서 getDom 메소드를 삭제합니다.
   - 컴포넌트의 $dom 은 직접 접근해 사용합니다.
- 프론트 directory와 file 이름 규칙을 변경합니다.
   - 파일명 : ButtonComponent -> button-component
   - 폴더명 : Button -> button

**Comment by TsooranKim** [comment]
네 좋습니다.
