### ISSUE TITLE
[document] README.md에 팀소개를 작성해야 합니다.

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/deal-15#6]
팀소개를 댓글로 남겨주세요.

**Comment by momongss** [comment]
### [이태형](https://github.com/momongss)

안녕하세요. 꿈 많은 개발자입니다. 힘들기도 하겠지만, 재밌게 활동했으면 좋겠습니다 ☺️☺️☺️

- 전공 : 정보통신공학
- 좋아하는 것 : 넷플릭스 보면서 맥주마시기.
- 제일 좋아하는 넷플릭스 드라마, 영화
  - 데리걸즈
  - 저니스 엔드

**Comment by TsooranKim** [comment]
[김태균](https://github.com/TsooranKim)

정말 다행히도 잘하는 것과 좋아하는 것이 일치하는 김태균이라고 합니다.
우아한테크캠프에서 다양한 분들과 같이 프로젝트를 하면서 협업하는 정신을 기르고자 합니다~
