### ISSUE TITLE
[document] pull request 방법

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/deal-15#7]
## PR 제목 작성 방법

pr의 제목은 **[ISSUE-TYPE/#ISSUE-ID] 간단한 설명** 으로 작성합니다.
대괄호 안에 들어가는 내용은 브런치 이름에서 keyword 부분을 제외한 것과 같습니다.

## PR 내용

코드의 내용을 다른 사람이 알 수 있도록 설명하는 글을 작성합니다.
리뷰어에게 요구하는 사항이나 제안점을 작성할 수도 있습니다.
참고할 만한 사항이 있으면 작성합니다.

## 메타 정보 설정

- **reviewer**: hotfix를 제외한 PR에는 반드시 리뷰어를 설정합니다.
- **assignees**: 본인으로 설정합니다.
- **labels**: 적절한 레이블을 선택합니다.
- **linked issues**: 관련된 이슈를 선택하여 연결합니다.

## 코드 리뷰

리뷰어는 해당 PR를 꼼꼼하게 리뷰합니다.
잘 못된 사항이나 오타 등이 있다면 수정을 요청합니다.
좋은 코드를 발견하면 칭찬합니다.

## 코드 허가

리뷰어는 해당 PR에 문제가 없다고 판단될 때 approve 합니다.

## 머지

PR 작성자는 PR이 모든 리뷰어에게 approved 됐을 때 직접 머지를 합니다.
머지는 반드시 **squash and merge**를 합니다.

**Comment by momongss** [comment]
네 꼼꼼히 읽어봤습니다. 😀😀

**Comment by TsooranKim** [comment]
넵 [위키](https://github.com/woowa-techcamp-2021/deal-15/wiki/Pull-requests-%EB%B0%A9%EB%B2%95)에 작성했습니다.
