### ISSUE TITLE
[document] eslint와 prettier, editorconfig 설정 제안

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/deal-15#8]
eslint와 prettier, editorconfig 사용 설정을 제안합니다.
살펴보시고 수정사항 말씀해주세요.

추후에도 필요하다면 계속 업데이트 할 수 있습니다.

### eslint

프로젝트에서 작성된 코드의 스타일을 강제하기 위해서 사용합니다.

### prettier

프로젝트에서 작성된 코드의 스타일을 교정하기 위해서 사용합니다.

### editorconfig

서로 다른 개발환경에서 editor의 설정을 일치 시키기 위해서 사용합니다.

## VSCode extensions

- [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
- [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)

## node.js packages

모두 `devDependencies`에 추가합니다.

```bash
$ npm i -D eslint prettier eslint-plugin-prettier eslint-config-prettier
```

- [eslint](https://www.npmjs.com/package/eslint)
- [prettier](https://www.npmjs.com/package/prettier)
- [eslint-plugin-prettier](https://www.npmjs.com/package/eslint-config-prettier)
- [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier)

**eslint-plugin-prettier**를 통해서 eslint를 prettier 설정에 맞춰서 린트를 강제하게 만듭니다.
**eslint-config-prettier**를 통해서 eslint의 기본설정을 모두 끄고 prettire를 중심으로 설정하게 만듭니다.

## vscode 설정

해당 설정은 `User`가 아닌 `Workspace`로 설정합니다.
**<project>/.vscode/settings.json** 에 위치합니다.

```json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true
}
```

## editorconfig

**<project>/.editorconfig** 에 위치합니다.

```
root = true

[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
```

## prettier

**<project>/.prettierrc** 에 위치합니다.

```json
{
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "useTabs": false,
  "trailingComma": "all",
  "printWidth": 100
}
```

## eslint

**<project>/.eslintrc.json** 에 위치합니다.

### client 용

```json
{
  "env": {
    "browser": true,
    "es6": true
  },
  "extends": ["plugin:prettier/recommended"],
  "plugins": ["prettier"],
  "parserOptions": {
    "sourceType": "module"
  },
  "rules": {
    "prettier/prettier": "error"
  }
}
```

### server 용

```json
{
  "env": {
    "node": true,
    "es6": true
  },
  "extends": ["plugin:prettier/recommended"],
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": "error"
  }
}
```

**Comment by momongss** [comment]
네 다 좋습니다. 차후 진행하다 더 필요한 사항이 있으면 이슈로 등록하겠습니다.

**Comment by TsooranKim** [comment]
넵 [위키](https://github.com/woowa-techcamp-2021/deal-15/wiki/eslint%EC%99%80-prettier,-editorconfig)에 등록했습니다.
